<?php require 'application/layouts/header.phtml'; ?>

    <ul>
        <li><a href="/index.php?controller=index&action=index">Index</a></li>
        <li><a href="/index.php?controller=calculator&action=min">Transforma a Minusculas</a></li>
        <li><a href="/index.php?controller=calculator&action=may">Transforma a Mayusculas</a></li>
        <li><a href="/index.php?controller=calculator&action=cmay">Transforma 1er Caracter Mayúsculas</a></li>
        <li><a href="/index.php?controller=calculator&action=count">Contar Caracteres</a></li>
        <li><a href="/index.php?controller=calculator&action=inverse">Invierte los Caracteres</a></li>
    </ul>

<?php require 'application/layouts/footer.phtml'; ?>